### ISSUE TITLE
What does hyperlog does?

### ISSUE THREAD

**Issue by hackerkid** [mafintosh/hyperlog#11]
Terms like Merkle DAG and scuttlebutt logs are new to me. Can someone explain in simple words what hyperlog does? I am trying to implement off line messaging in a peer to peer network.  Can hyperlog be used to solve this issue?

What I meant by off line messaging is the ability to send message to a node even if it's offline at the time of sending. 

Sorry if I am completely off the topic

**Comment by mafintosh** [comment]
No your question is completely valid :) The "why" in the docs are kinda lacking i guess.

Hyperlog is a graph data structure that distributes very well over a bunch of computers on the internet. It works by being content addressed (meaning that the id of a graph node is the hash of the graph node value and any links to other nodes this graph node might have). By having node id's be hashes you can (more or less) guarantee that the graph wont have any cycles since that would require a hash collision.

The downside is that you have to map all your data to this graph format and that all peers have to replicate the entire graph (currently).

We actually use this in our Friends offline chat app so it can definitely fit the chat problem. I would probably do it similar to this

``` js
var log = hyperlog(...)

log.createReadStream({live: true})
  .on('data', function (data) {
     // since this is a live read stream this is called every time data is added to the log
     var val = JSON.parse(data.value.toString())
     console.log(val.username + '>' + val.message)
  })

function chat (username, message) {
  // append a message to the log to chat
  log.append(JSON.stringify({username: username, message: message}))
}
```

Now you also need to replicate the log to other people you want to chat with. To do this you need to pipe a replication stream to another peer.

``` js
var stream = log.replicate({live: true})
streamToAnotherPeer.pipe(stream).pipe(streamToAnotherPeer)
```

Does that make sense?

**Comment by hackerkid** [comment]
Thanks a lot for replying.  I have one more doubt. Assume A is having a conversation with B. Now A wants to send a message to B.

To implement this I would write something like this

```javascript

// Client A

log1.append(JSON.stringify({username: username, message: message})) //log1 belongs to A

send_message(B, log1); // a function to send the log from A to other node B

// Client B

var s1 = log1.replicate()
var s2 = log2.replicate() // log2 is the log of player B

s1.pipe(s2).pipe(s1); 

log2.createReadStream({live: true})
  .on('data', function (data) {
     // since this is a live read stream this is called every time data is added to the log1
     var val = JSON.parse(data.value.toString())
     console.log(val.username + '>' + val.message)
  })

```
Is this how the code would be written?

**Comment by Ivshti** [comment]
I'd like to go a bit off-topic and ask how to avoid the disadvantage of replicating the whole graph. In my opinion, avoid this has a huge technical potential. 

Of course, one of the options is doing it similar to MongoDB's sharding, i.e. splitting the data based on the range of the value of a hash function. This however has many side implications and as much as I understand the matter, totally changes the design & goals of hyperlog. 

The second option is making a system where every node is aware of all the keys, but the values are replicated on demand. This seems practical & useful to me.

**Comment by mafintosh** [comment]
@Ivshti hyperlog uses an append-only log per user to index the merkle dag. every time a user adds a node to the graph it is indexed as the latest entry in the users own append-only log. the way it replicates is that it'll look at the current heads of the graph and start replicating the logs the heads are part of. if you receive a node that has links that point to another log you replicate that log as well if the link refers to a newer sequence than you currently have locally for that log. all logs are replicated by sending oldest->newest entries since that makes log digest easy (if you have an entry with seq 5 it is implied that you'll also have 4,3,2,1 because thats the order we send nodes in).

now the goal of the next generation of hyperlog is to replicate the logs newest->oldest. the main change here is that the log digest will be a series of ranges instead of a single seq number. fx you might have entries 5,4,3 and then just 1. my current idea is using a [flat-tree](https://github.com/mafintosh/flat-tree) to index the ranges you have and to easily ask for the ranges you are looking for (fx asking for 3 in a flat-tree implies that you are asking for 0,2,4,6)

**Comment by mafintosh** [comment]
@hackerkid that looks about right though i'm not 100% sure what `send_message` does in your example

**Comment by hackerkid** [comment]
@mafintosh I would be using the send_message function to exchange the logs between the nodes. I am hoping for using the Tox protocol for achieving this. :smiley:

**Comment by mafintosh** [comment]
@hackerkid cool! ping me when you have something online i can try

**Comment by hackerkid** [comment]
@mafintosh Sure. Thanks for helping out. @Ivshti I am closing this issue.
