### ISSUE TITLE
Hyperlog vs Hypercore?

### ISSUE THREAD

**Issue by tvedtorama** [mafintosh/hyperlog#38]
Hi,

I'm trying to get my head around this web of very amazing decentralized technologies - and find hyperlog very appealing for its modularity and simplicity. Thumbs up!

However, there is another project - [hypercore](https://github.com/mafintosh/hypercore/). This project does not seem to be structured as a graph, seems to be recommended for exchange of big datasets (hyperdrive) and might be less bit less modular.  Is this correct?

Is it possible to explain the differences in a few words?

**Comment by hackergrrl** [comment]
Good question.

You're right that hyperlog models a DAG (directed acyclic graph). It models a graph, but underneath it is a collection of different users' append-only logs. hyper**core** models a single append-only log.

Hyperlog is perhaps the less modular one: it builds the append-only log mechanism *and* the indexes & logic to model a DAG on top, all in a single module.

Another distinction is partial sync. Hyperlog's replication mechanism *must* exchange all data of all append-only log entries in order to function. Hypercore, however, operates fine with only a partial subset of entries replicated. This property is held on the higher level modules built on hypercore, like hyperdrive and hyperdb.

**Comment by hackergrrl** [comment]
Also, the way data is stored varies. Hyperlog uses LevelDB, and hypercore uses a *much* more efficient and simple [random-access-file](https://github.com/mafintosh/random-access-file) interface. In general, performance on hypercore-based modules is significantly better.

**Comment by tvedtorama** [comment]
Thank you,

this makes much sense!  I have found several modules around the place that can be used to extend hyperlog, some of them with just a few highly readable lines of code.  This makes it very easy to reason about the core components.  From what you're writing above, one should expect no less of hypercore?

So, say that I'm working on a project with some scaleability requirements - yet otherwise unclear specifications - I guess it might be worth researching the hypercore family before settling on hyperlog...

I guess this thread can be closed, but I think there might be more people than me wondering about this differentiation.

**Comment by hackergrrl** [comment]
> So, say that I'm working on a project with some scaleability requirements - yet otherwise unclear specifications - I guess it might be worth researching the hypercore family before settling on hyperlog...

Yes, that's my opinion. Another factor to consider is community: the hypercore family is seeing much more active development and funding currently.

**Comment by tvedtorama** [comment]
Excellent.  And from your answer above, and [on the hyperlog-index project](https://github.com/substack/hyperlog-index/issues/6#issuecomment-331505735) - partial replication is no walk in the park using the hyperlog, which could be a very important thing in some contexts.
