### ISSUE TITLE
TypeError: keys[0].split is not a function

### ISSUE THREAD

**Issue by beingmohit** [mafintosh/hyperlog#39]
```
const memdb = require('memdb')
const hyperlog = require('hyperlog')

const log = hyperlog(memdb()) 
```

throws:

```
self.changes = Math.max(self.changes, keys && keys.length ? lexint.unpack(keys[0].split('!').pop(), 'hex') : 0)
                                                                                        ^
TypeError: keys[0].split is not a function
    at /home/mohit/projects/libp2p-dagdb/node_modules/hyperlog/index.js:76:89
    at f (/home/mohit/projects/libp2p-dagdb/node_modules/once/once.js:25:25)
    at ReadStream.<anonymous> (/home/mohit/projects/libp2p-dagdb/node_modules/stream-collector/index.js:15:5)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (/home/mohit/projects/libp2p-dagdb/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by beingmohit** [comment]
Same for levelup+leveldown

**Comment by hackergrrl** [comment]
Hey @beingmohit. Thanks for reporting. This is surprising, since no keys should be in the database yet, and that codepath wouldn't be hit. I wasn't able to reproduce this on my machine (Linux 4.9.33 x86_64 with Node 6.9.5). What OS and version of Node are you running?

Also, it might be worth trying to reproduce this in a fresh directory with just hyperlog and memdb; I notice that you're running this code in the context of another codebase it looks like?

**Comment by beingmohit** [comment]
I tried again. and it seems to be working fine now. Maybe I missed something earlier. I will try to reproduce it and update. Closing the issue meanwhile. Thanks and sorry! 

Node Version: 8.8.1
OS:  4.13.12-1-ARCH x86_64 GNU/Linux

**Comment by hackergrrl** [comment]
No worries. Glad it's working.

**Comment by edowado** [comment]
same problem with levelup and leveljs
replacing them with level-browserify fixed the problem
